version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew :app:dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Jacoco Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Jacoco Code Coverage Report
          command: ./gradlew createDebugCoverageReport
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
