version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew :app:dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Jacoco Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Jacoco Run Test Coverage
          command: ./gradlew test testDebugUnitTest sonarqube
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
