version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
#      - run:
#          name: Download Dependencies
#          command: ./gradlew :app:dependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonarqube

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
