version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

aliases:
  - &working_directory ~/CChat

executors:
  android-executor:
    docker:
      - image: circleci/android:api-29

jobs:
  sonar-scan:
    working_directory: *working_directory
    executor: android-executor
    resource_class: medium
    steps:
      - sonarcloud/scan

  build:
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew :app:dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Jacoco Run Unit Tests
          command: ./gradlew testDebugUnitTest
      - run:
          name: Analyze on SonarCloud
          command: ./gradlew build sonarqube
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  main:
    jobs:
      - sonar-scan:
          context: SonarCloud
